In [3]:
import sys; sys.path.append("../") # For relative imports

from utils.experiment_utils import *

%load_ext autoreload
%autoreload 2

Read in all saved results and make Latex table

**Note**: Before running this notebook, run `sh run_experiment.sh`.

Formatting notes: To get multiple row levels, set a multi-index. To get multiple column levels, concatenate dataframes along axis=1.

In [29]:
#datasets = {'DDR': '../results/paper/varying_n/focal-ddr'}
datasets = {'DDR': '../results/paper//varying_n/ddr-cp-aware'}

score_functions = {'softmax': '$\softmax$',
                  'APS': '$\APS$',
                  'RAPS': '$\RAPS$'}

methods = {'standard': '$\standard$', 
            'classwise': '$\classwise$',
            'cluster_random': '$\clustered$'} 

calibration_sampling = 'random' # 'random' or 'balanced'

## Main table
This is Table 1 of the paper.

In [30]:
# GENERATE TABLE - three n's and excluding marginal coverage
n_totalcals = {50: '$n_{\\text{avg}}=50$', 100: '$n_{\\text{avg}}=100$', 150: '$n_{\\text{avg}}=150$', 
               200: '$n_{\\text{avg}}=200$', 300: '$n_{\\text{avg}}=300$'}

horizontal_dict = {}
for n_totalcal, n_name in n_totalcals.items():
    vertical_list = []
    for dataset, save_folder in datasets.items():
        for score, score_name in score_functions.items():
            for method, method_name in methods.items(): 

                folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
                print(folder)
                df = average_results_across_seeds(folder, print_results=False, methods=methods.keys()) # df = results DataFrame
                s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
                               'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
                                       f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
                               'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
                                               f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})"})
#                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
                vertical_list.append(pd.DataFrame(s).transpose())                                        

    df = pd.concat(vertical_list, ignore_index=True)                                                     
    df = df.set_index(['Dataset', 'Score func.', 'Method'])
    horizontal_dict[n_name] = df

df = pd.concat(horizontal_dict, axis=1)
df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
    escape=False) # So that backslashes are printed as `\' rather than '\textbackslash'
                 
# Post-process
df_str = df_str.replace('lllllllllll', 'lllcrcrcrcr')
df_str = df_str.replace('\\multicolumn{2}{c}{$n_{\\text{avg}}=375$} \\\\',
               '\\multicolumn{2}{c}{$n_{\\text{avg}}=375$} \\\\ \\cmidrule(lr){4-5}\\cmidrule(lr){6-7}\\cmidrule(lr){8-9}\\cmidrule(lr){10-11}\\\\')
df_str = df_str.replace('DDR', '\midrule\nDDR')
# Add horizontal lines between methods
df_str = df_str.replace('& $\APS$', '\cline{3-11} & $\APS$')
df_str = df_str.replace('& $\RAPS$', '\cline{3-11} & $\RAPS$')
print(df_str)

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.775457,1.302591,30.824777,3.030429,1.507872,0.053975,0.898802,0.008957,0.36,0.035777,13.674499,1.465494,5.685865,0.515310
1,classwise,5.176826,0.290046,10.000000,0.000000,2.842042,0.118910,0.901597,0.008485,0.00,0.000000,NaN,NaN,5.659608,0.391093
2,cluster_random,10.751334,1.600358,27.034233,4.458209,1.588648,0.083571,0.909241,0.013121,0.32,0.043818,12.923565,1.671142,5.374741,0.384445

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.775457,1.302591,30.824777,3.030429,1.507872,0.053975,0.898802,0.008957,0.36,0.035777,13.674499,1.465494,5.685865,0.515310
1,classwise,5.176826,0.290046,10.000000,0.000000,2.842042,0.118910,0.901597,0.008485,0.00,0.000000,NaN,NaN,5.659608,0.391093
2,cluster_random,10.751334,1.600358,27.034233,4.458209,1.588648,0.083571,0.909241,0.013121,0.32,0.043818,12.923565,1.671142,5.374741,0.384445

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.775457,1.302591,30.824777,3.030429,1.507872,0.053975,0.898802,0.008957,0.36,0.035777,13.674499,1.465494,5.685865,0.515310
1,classwise,5.176826,0.290046,10.000000,0.000000,2.842042,0.118910,0.901597,0.008485,0.00,0.000000,NaN,NaN,5.659608,0.391093
2,cluster_random,10.751334,1.600358,27.034233,4.458209,1.588648,0.083571,0.909241,0.013121,0.32,0.043818,12.923565,1.671142,5.374741,0.384445

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.622188,0.524904,23.741982,0.456152,1.699601,0.026238,0.890930,0.004474,0.28,0.043818,10.053400,0.731424,2.897340,0.308056
1,classwise,5.137943,0.411405,10.000000,0.000000,2.941985,0.107405,0.884084,0.009067,0.00,0.000000,3.237827,0.694366,6.437511,0.414626
2,cluster_random,8.873768,1.846690,21.119459,4.016843,1.778152,0.126595,0.896520,0.020508,0.28,0.091214,9.928158,2.108704,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.622188,0.524904,23.741982,0.456152,1.699601,0.026238,0.890930,0.004474,0.28,0.043818,10.053400,0.731424,2.897340,0.308056
1,classwise,5.137943,0.411405,10.000000,0.000000,2.941985,0.107405,0.884084,0.009067,0.00,0.000000,3.237827,0.694366,6.437511,0.414626
2,cluster_random,8.873768,1.846690,21.119459,4.016843,1.778152,0.126595,0.896520,0.020508,0.28,0.091214,9.928158,2.108704,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.622188,0.524904,23.741982,0.456152,1.699601,0.026238,0.890930,0.004474,0.28,0.043818,10.053400,0.731424,2.897340,0.308056
1,classwise,5.137943,0.411405,10.000000,0.000000,2.941985,0.107405,0.884084,0.009067,0.00,0.000000,3.237827,0.694366,6.437511,0.414626
2,cluster_random,8.873768,1.846690,21.119459,4.016843,1.778152,0.126595,0.896520,0.020508,0.28,0.091214,9.928158,2.108704,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.691167,0.521063,24.298932,0.616076,1.687735,0.024113,0.891900,0.004419,0.28,0.043818,10.122443,0.718271,2.966060,0.279270
1,classwise,5.225704,0.309004,10.000000,0.000000,2.963149,0.100123,0.884598,0.008803,0.00,0.000000,3.524836,0.550359,6.308246,0.347882
2,cluster_random,9.214869,1.685632,21.977123,3.914773,1.751512,0.115922,0.895094,0.019517,0.28,0.091214,10.791423,1.619292,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.691167,0.521063,24.298932,0.616076,1.687735,0.024113,0.891900,0.004419,0.28,0.043818,10.122443,0.718271,2.966060,0.279270
1,classwise,5.225704,0.309004,10.000000,0.000000,2.963149,0.100123,0.884598,0.008803,0.00,0.000000,3.524836,0.550359,6.308246,0.347882
2,cluster_random,9.214869,1.685632,21.977123,3.914773,1.751512,0.115922,0.895094,0.019517,0.28,0.091214,10.791423,1.619292,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=50/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.691167,0.521063,24.298932,0.616076,1.687735,0.024113,0.891900,0.004419,0.28,0.043818,10.122443,0.718271,2.966060,0.279270
1,classwise,5.225704,0.309004,10.000000,0.000000,2.963149,0.100123,0.884598,0.008803,0.00,0.000000,3.524836,0.550359,6.308246,0.347882
2,cluster_random,9.214869,1.685632,21.977123,3.914773,1.751512,0.115922,0.895094,0.019517,0.28,0.091214,10.791423,1.619292,NaN,NaN

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.732484,0.552583,30.731567,1.188443,1.490295,0.022738,0.898280,0.004384,0.4,0.0,13.103835,0.730130,6.247079,0.174775
1,classwise,3.766228,0.379880,8.608385,0.914125,2.305221,0.141864,0.897174,0.006320,0.0,0.0,2.714137,0.773902,4.207171,0.786157
2,cluster_random,11.737048,0.791140,30.489344,2.168331,1.496622,0.037154,0.898464,0.006612,0.4,0.0,13.755984,0.767791,5.526470,0.479399

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.732484,0.552583,30.731567,1.188443,1.490295,0.022738,0.898280,0.004384,0.4,0.0,13.103835,0.730130,6.247079,0.174775
1,classwise,3.766228,0.379880,8.608385,0.914125,2.305221,0.141864,0.897174,0.006320,0.0,0.0,2.714137,0.773902,4.207171,0.786157
2,cluster_random,11.737048,0.791140,30.489344,2.168331,1.496622,0.037154,0.898464,0.006612,0.4,0.0,13.755984,0.767791,5.526470,0.479399

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,11.732484,0.552583,30.731567,1.188443,1.490295,0.022738,0.898280,0.004384,0.4,0.0,13.103835,0.730130,6.247079,0.174775
1,classwise,3.766228,0.379880,8.608385,0.914125,2.305221,0.141864,0.897174,0.006320,0.0,0.0,2.714137,0.773902,4.207171,0.786157
2,cluster_random,11.737048,0.791140,30.489344,2.168331,1.496622,0.037154,0.898464,0.006612,0.4,0.0,13.755984,0.767791,5.526470,0.479399

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.394860,0.550669,22.323658,1.228684,1.722973,0.034621,0.895147,0.005578,0.28,0.043818,10.072129,0.577771,2.858445,0.178316
1,classwise,3.974171,0.324996,8.959263,0.625093,2.446253,0.138150,0.893980,0.008944,0.00,0.000000,2.593053,0.344652,4.927129,0.264804
2,cluster_random,8.108752,0.788969,21.587114,1.557362,1.740786,0.052357,0.897297,0.008509,0.24,0.035777,10.858073,0.846350,2.393003,0.283922

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.394860,0.550669,22.323658,1.228684,1.722973,0.034621,0.895147,0.005578,0.28,0.043818,10.072129,0.577771,2.858445,0.178316
1,classwise,3.974171,0.324996,8.959263,0.625093,2.446253,0.138150,0.893980,0.008944,0.00,0.000000,2.593053,0.344652,4.927129,0.264804
2,cluster_random,8.108752,0.788969,21.587114,1.557362,1.740786,0.052357,0.897297,0.008509,0.24,0.035777,10.858073,0.846350,2.393003,0.283922

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.394860,0.550669,22.323658,1.228684,1.722973,0.034621,0.895147,0.005578,0.28,0.043818,10.072129,0.577771,2.858445,0.178316
1,classwise,3.974171,0.324996,8.959263,0.625093,2.446253,0.138150,0.893980,0.008944,0.00,0.000000,2.593053,0.344652,4.927129,0.264804
2,cluster_random,8.108752,0.788969,21.587114,1.557362,1.740786,0.052357,0.897297,0.008509,0.24,0.035777,10.858073,0.846350,2.393003,0.283922

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.470110,0.522264,23.437155,0.883919,1.708538,0.030203,0.894840,0.005344,0.24,0.035777,10.247572,0.600008,2.813597,0.206562
1,classwise,4.065021,0.290251,8.959263,0.625093,2.503993,0.118471,0.893919,0.009288,0.00,0.000000,2.809987,0.347364,4.940251,0.214470
2,cluster_random,8.597412,0.732540,23.061738,1.335776,1.721990,0.048391,0.896806,0.008352,0.24,0.035777,11.348704,0.738326,2.316275,0.296868

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.470110,0.522264,23.437155,0.883919,1.708538,0.030203,0.894840,0.005344,0.24,0.035777,10.247572,0.600008,2.813597,0.206562
1,classwise,4.065021,0.290251,8.959263,0.625093,2.503993,0.118471,0.893919,0.009288,0.00,0.000000,2.809987,0.347364,4.940251,0.214470
2,cluster_random,8.597412,0.732540,23.061738,1.335776,1.721990,0.048391,0.896806,0.008352,0.24,0.035777,11.348704,0.738326,2.316275,0.296868

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=100/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.470110,0.522264,23.437155,0.883919,1.708538,0.030203,0.894840,0.005344,0.24,0.035777,10.247572,0.600008,2.813597,0.206562
1,classwise,4.065021,0.290251,8.959263,0.625093,2.503993,0.118471,0.893919,0.009288,0.00,0.000000,2.809987,0.347364,4.940251,0.214470
2,cluster_random,8.597412,0.732540,23.061738,1.335776,1.721990,0.048391,0.896806,0.008352,0.24,0.035777,11.348704,0.738326,2.316275,0.296868

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.142422,0.603020,31.133280,1.322334,1.485363,0.016937,0.896873,0.003592,0.40,0.000000,13.616858,0.773684,6.244679,0.104748
1,classwise,3.560317,0.373695,9.781284,1.783028,2.034265,0.089119,0.899468,0.006020,0.04,0.035777,2.360544,0.867018,3.701207,0.351238
2,cluster_random,4.928457,0.581712,13.595539,2.010471,1.896341,0.059786,0.901996,0.007413,0.12,0.043818,6.944400,1.722047,3.086127,0.908650

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.142422,0.603020,31.133280,1.322334,1.485363,0.016937,0.896873,0.003592,0.40,0.000000,13.616858,0.773684,6.244679,0.104748
1,classwise,3.560317,0.373695,9.781284,1.783028,2.034265,0.089119,0.899468,0.006020,0.04,0.035777,2.360544,0.867018,3.701207,0.351238
2,cluster_random,4.928457,0.581712,13.595539,2.010471,1.896341,0.059786,0.901996,0.007413,0.12,0.043818,6.944400,1.722047,3.086127,0.908650

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.142422,0.603020,31.133280,1.322334,1.485363,0.016937,0.896873,0.003592,0.40,0.000000,13.616858,0.773684,6.244679,0.104748
1,classwise,3.560317,0.373695,9.781284,1.783028,2.034265,0.089119,0.899468,0.006020,0.04,0.035777,2.360544,0.867018,3.701207,0.351238
2,cluster_random,4.928457,0.581712,13.595539,2.010471,1.896341,0.059786,0.901996,0.007413,0.12,0.043818,6.944400,1.722047,3.086127,0.908650

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.401426,0.517109,22.960422,0.873046,1.741450,0.020730,0.897405,0.003636,0.32,0.043818,10.167283,0.686274,3.125171,0.239581
1,classwise,3.096782,0.395584,6.913793,1.305940,2.163872,0.068487,0.895542,0.004999,0.00,0.000000,2.309135,0.467879,3.520268,0.647812
2,cluster_random,5.161746,0.388485,12.089201,1.280576,1.990086,0.086210,0.900399,0.008352,0.16,0.066933,6.729693,0.478882,2.885586,0.631391

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.401426,0.517109,22.960422,0.873046,1.741450,0.020730,0.897405,0.003636,0.32,0.043818,10.167283,0.686274,3.125171,0.239581
1,classwise,3.096782,0.395584,6.913793,1.305940,2.163872,0.068487,0.895542,0.004999,0.00,0.000000,2.309135,0.467879,3.520268,0.647812
2,cluster_random,5.161746,0.388485,12.089201,1.280576,1.990086,0.086210,0.900399,0.008352,0.16,0.066933,6.729693,0.478882,2.885586,0.631391

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.401426,0.517109,22.960422,0.873046,1.741450,0.020730,0.897405,0.003636,0.32,0.043818,10.167283,0.686274,3.125171,0.239581
1,classwise,3.096782,0.395584,6.913793,1.305940,2.163872,0.068487,0.895542,0.004999,0.00,0.000000,2.309135,0.467879,3.520268,0.647812
2,cluster_random,5.161746,0.388485,12.089201,1.280576,1.990086,0.086210,0.900399,0.008352,0.16,0.066933,6.729693,0.478882,2.885586,0.631391

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.760597,0.459534,23.995496,0.686202,1.719295,0.020312,0.896873,0.004003,0.32,0.043818,11.220377,0.507742,2.753811,0.286106
1,classwise,3.066966,0.351411,7.100097,1.259749,2.222754,0.076102,0.896208,0.005191,0.00,0.000000,2.591504,0.467291,3.340862,0.541798
2,cluster_random,5.483411,0.350121,13.179881,1.419198,2.000931,0.095605,0.899601,0.007989,0.20,0.056569,7.841290,0.838666,2.965849,0.671996

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.760597,0.459534,23.995496,0.686202,1.719295,0.020312,0.896873,0.004003,0.32,0.043818,11.220377,0.507742,2.753811,0.286106
1,classwise,3.066966,0.351411,7.100097,1.259749,2.222754,0.076102,0.896208,0.005191,0.00,0.000000,2.591504,0.467291,3.340862,0.541798
2,cluster_random,5.483411,0.350121,13.179881,1.419198,2.000931,0.095605,0.899601,0.007989,0.20,0.056569,7.841290,0.838666,2.965849,0.671996

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=150/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.760597,0.459534,23.995496,0.686202,1.719295,0.020312,0.896873,0.004003,0.32,0.043818,11.220377,0.507742,2.753811,0.286106
1,classwise,3.066966,0.351411,7.100097,1.259749,2.222754,0.076102,0.896208,0.005191,0.00,0.000000,2.591504,0.467291,3.340862,0.541798
2,cluster_random,5.483411,0.350121,13.179881,1.419198,2.000931,0.095605,0.899601,0.007989,0.20,0.056569,7.841290,0.838666,2.965849,0.671996

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.564001,0.822528,32.040598,1.927421,1.479100,0.023686,0.895065,0.006078,0.40,0.000000,14.170571,1.079100,6.137718,0.227264
1,classwise,3.383462,0.463621,8.984575,1.793389,1.970464,0.059115,0.903774,0.006955,0.04,0.035777,NaN,NaN,3.422695,0.532860
2,cluster_random,13.012989,0.854159,33.160451,2.509665,1.477721,0.042951,0.892671,0.008014,0.40,0.000000,14.724890,1.143752,6.165384,0.339206

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.564001,0.822528,32.040598,1.927421,1.479100,0.023686,0.895065,0.006078,0.40,0.000000,14.170571,1.079100,6.137718,0.227264
1,classwise,3.383462,0.463621,8.984575,1.793389,1.970464,0.059115,0.903774,0.006955,0.04,0.035777,NaN,NaN,3.422695,0.532860
2,cluster_random,13.012989,0.854159,33.160451,2.509665,1.477721,0.042951,0.892671,0.008014,0.40,0.000000,14.724890,1.143752,6.165384,0.339206

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,12.564001,0.822528,32.040598,1.927421,1.479100,0.023686,0.895065,0.006078,0.40,0.000000,14.170571,1.079100,6.137718,0.227264
1,classwise,3.383462,0.463621,8.984575,1.793389,1.970464,0.059115,0.903774,0.006955,0.04,0.035777,NaN,NaN,3.422695,0.532860
2,cluster_random,13.012989,0.854159,33.160451,2.509665,1.477721,0.042951,0.892671,0.008014,0.40,0.000000,14.724890,1.143752,6.165384,0.339206

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.640776,0.541758,23.381896,0.740488,1.744848,0.023031,0.897533,0.004825,0.32,0.043818,11.101495,0.945296,2.876022,0.255841
1,classwise,2.613839,0.321320,6.590588,1.355679,2.127649,0.060466,0.899129,0.005328,0.00,0.000000,2.202296,0.373938,2.434670,0.605492
2,cluster_random,8.641905,0.674439,22.402875,1.323414,1.747968,0.045610,0.897388,0.008425,0.36,0.066933,11.846377,1.073435,2.631337,0.356083

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.640776,0.541758,23.381896,0.740488,1.744848,0.023031,0.897533,0.004825,0.32,0.043818,11.101495,0.945296,2.876022,0.255841
1,classwise,2.613839,0.321320,6.590588,1.355679,2.127649,0.060466,0.899129,0.005328,0.00,0.000000,2.202296,0.373938,2.434670,0.605492
2,cluster_random,8.641905,0.674439,22.402875,1.323414,1.747968,0.045610,0.897388,0.008425,0.36,0.066933,11.846377,1.073435,2.631337,0.356083

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.640776,0.541758,23.381896,0.740488,1.744848,0.023031,0.897533,0.004825,0.32,0.043818,11.101495,0.945296,2.876022,0.255841
1,classwise,2.613839,0.321320,6.590588,1.355679,2.127649,0.060466,0.899129,0.005328,0.00,0.000000,2.202296,0.373938,2.434670,0.605492
2,cluster_random,8.641905,0.674439,22.402875,1.323414,1.747968,0.045610,0.897388,0.008425,0.36,0.066933,11.846377,1.073435,2.631337,0.356083

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,9.107552,0.550753,24.500777,0.878494,1.720392,0.019938,0.896807,0.004695,0.32,0.043818,11.832993,1.140319,2.882123,0.239304
1,classwise,2.615253,0.383375,6.538492,1.435287,2.167126,0.081534,0.899419,0.005852,0.00,0.000000,2.534179,0.501061,2.395088,0.832565
2,cluster_random,8.786562,0.535319,23.519814,0.816583,1.731422,0.036674,0.898403,0.006687,0.36,0.066933,11.172968,0.832344,2.971312,0.333540

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,9.107552,0.550753,24.500777,0.878494,1.720392,0.019938,0.896807,0.004695,0.32,0.043818,11.832993,1.140319,2.882123,0.239304
1,classwise,2.615253,0.383375,6.538492,1.435287,2.167126,0.081534,0.899419,0.005852,0.00,0.000000,2.534179,0.501061,2.395088,0.832565
2,cluster_random,8.786562,0.535319,23.519814,0.816583,1.731422,0.036674,0.898403,0.006687,0.36,0.066933,11.172968,0.832344,2.971312,0.333540

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=200/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,9.107552,0.550753,24.500777,0.878494,1.720392,0.019938,0.896807,0.004695,0.32,0.043818,11.832993,1.140319,2.882123,0.239304
1,classwise,2.615253,0.383375,6.538492,1.435287,2.167126,0.081534,0.899419,0.005852,0.00,0.000000,2.534179,0.501061,2.395088,0.832565
2,cluster_random,8.786562,0.535319,23.519814,0.816583,1.731422,0.036674,0.898403,0.006687,0.36,0.066933,11.172968,0.832344,2.971312,0.333540

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,10.599177,0.440158,26.739516,0.854579,1.529521,0.006992,0.907270,0.002000,0.4,0.0,11.572597,0.546003,6.705494,0.209544
1,classwise,2.796554,0.483484,6.996732,1.354412,1.993262,0.045821,0.907535,0.005834,0.0,0.0,NaN,NaN,2.789706,0.635817
2,cluster_random,10.342639,0.524665,26.447729,1.067938,1.550798,0.033115,0.909397,0.004752,0.4,0.0,12.904428,1.106571,5.828970,0.650846

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,10.599177,0.440158,26.739516,0.854579,1.529521,0.006992,0.907270,0.002000,0.4,0.0,11.572597,0.546003,6.705494,0.209544
1,classwise,2.796554,0.483484,6.996732,1.354412,1.993262,0.045821,0.907535,0.005834,0.0,0.0,NaN,NaN,2.789706,0.635817
2,cluster_random,10.342639,0.524665,26.447729,1.067938,1.550798,0.033115,0.909397,0.004752,0.4,0.0,12.904428,1.106571,5.828970,0.650846

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=softmax/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,10.599177,0.440158,26.739516,0.854579,1.529521,0.006992,0.907270,0.002000,0.4,0.0,11.572597,0.546003,6.705494,0.209544
1,classwise,2.796554,0.483484,6.996732,1.354412,1.993262,0.045821,0.907535,0.005834,0.0,0.0,NaN,NaN,2.789706,0.635817
2,cluster_random,10.342639,0.524665,26.447729,1.067938,1.550798,0.033115,0.909397,0.004752,0.4,0.0,12.904428,1.106571,5.828970,0.650846

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,7.533252,0.412986,20.485708,0.561719,1.772340,0.006801,0.903546,0.001731,0.28,0.043818,9.542007,0.887596,3.225980,0.392551
1,classwise,2.737830,0.377954,7.104575,1.083060,2.159131,0.050725,0.905230,0.003069,0.00,0.000000,NaN,NaN,3.099687,0.582674
2,cluster_random,7.483137,0.467539,19.653545,0.690413,1.782181,0.025628,0.905230,0.003824,0.28,0.043818,10.507906,0.694988,2.841513,0.405000

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,7.533252,0.412986,20.485708,0.561719,1.772340,0.006801,0.903546,0.001731,0.28,0.043818,9.542007,0.887596,3.225980,0.392551
1,classwise,2.737830,0.377954,7.104575,1.083060,2.159131,0.050725,0.905230,0.003069,0.00,0.000000,NaN,NaN,3.099687,0.582674
2,cluster_random,7.483137,0.467539,19.653545,0.690413,1.782181,0.025628,0.905230,0.003824,0.28,0.043818,10.507906,0.694988,2.841513,0.405000

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=APS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,7.533252,0.412986,20.485708,0.561719,1.772340,0.006801,0.903546,0.001731,0.28,0.043818,9.542007,0.887596,3.225980,0.392551
1,classwise,2.737830,0.377954,7.104575,1.083060,2.159131,0.050725,0.905230,0.003069,0.00,0.000000,NaN,NaN,3.099687,0.582674
2,cluster_random,7.483137,0.467539,19.653545,0.690413,1.782181,0.025628,0.905230,0.003824,0.28,0.043818,10.507906,0.694988,2.841513,0.405000

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.207816,0.442674,21.674194,0.871082,1.749025,0.007454,0.903191,0.001569,0.32,0.043818,10.992401,0.862237,2.991281,0.493148
1,classwise,2.660966,0.389754,7.120594,1.323356,2.219504,0.071689,0.904255,0.002894,0.00,0.000000,NaN,NaN,3.145792,0.783804
2,cluster_random,7.850342,0.468592,20.503791,0.747520,1.770035,0.026575,0.906649,0.003982,0.28,0.043818,11.042441,0.853364,3.005108,0.346521

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.207816,0.442674,21.674194,0.871082,1.749025,0.007454,0.903191,0.001569,0.32,0.043818,10.992401,0.862237,2.991281,0.493148
1,classwise,2.660966,0.389754,7.120594,1.323356,2.219504,0.071689,0.904255,0.002894,0.00,0.000000,NaN,NaN,3.145792,0.783804
2,cluster_random,7.850342,0.468592,20.503791,0.747520,1.770035,0.026575,0.906649,0.003982,0.28,0.043818,11.042441,0.853364,3.005108,0.346521

../results/paper//varying_n/ddr-cp-aware/random_calset/n_totalcal=300/score=RAPS/

,method,class_cov_gap_mean,class_cov_gap_se,max_class_cov_gap_mean,max_class_cov_gap_se,avg_set_size_mean,avg_set_size_se,marginal_cov_mean,marginal_cov_se,very_undercovered_mean,very_undercovered_se,undercov_gap_mean,undercov_gap_se,overcov_gap_mean,overcov_gap_se
0,standard,8.207816,0.442674,21.674194,0.871082,1.749025,0.007454,0.903191,0.001569,0.32,0.043818,10.992401,0.862237,2.991281,0.493148
1,classwise,2.660966,0.389754,7.120594,1.323356,2.219504,0.071689,0.904255,0.002894,0.00,0.000000,NaN,NaN,3.145792,0.783804
2,cluster_random,7.850342,0.468592,20.503791,0.747520,1.770035,0.026575,0.906649,0.003982,0.28,0.043818,11.042441,0.853364,3.005108,0.346521

\begin{tabular}{lllcrcrcrcrll}
\toprule
 &  &  & \multicolumn{2}{c}{$n_{\text{avg}}=50$} & \multicolumn{2}{c}{$n_{\text{avg}}=100$} & \multicolumn{2}{c}{$n_{\text{avg}}=150$} & \multicolumn{2}{c}{$n_{\text{avg}}=200$} & \multicolumn{2}{c}{$n_{\text{avg}}=300$} \\
 &  &  & CovGap & AvgSize & CovGap & AvgSize & CovGap & AvgSize & CovGap & AvgSize & CovGap & AvgSize \\
Dataset & Score func. & Method &  &  &  &  &  &  &  &  &  &  \\
\midrule
\multirow[t]{9}{*}{\midrule
DDR} & \multirow[t]{3}{*}{$\softmax$} & $\standard$ & 11.8 (1.3) & 1.5 (0.1) & 11.7 (0.6) & 1.5 (0.0) & 12.1 (0.6) & 1.5 (0.0) & 12.6 (0.8) & 1.5 (0.0) & 10.6 (0.4) & 1.5 (0.0) \\
 &  & $\classwise$ & 5.2 (0.3) & 2.8 (0.1) & 3.8 (0.4) & 2.3 (0.1) & 3.6 (0.4) & 2.0 (0.1) & 3.4 (0.5) & 2.0 (0.1) & 2.8 (0.5) & 2.0 (0.0) \\
 &  & $\clustered$ & 10.8 (1.6) & 1.6 (0.1) & 11.7 (0.8) & 1.5 (0.0) & 4.9 (0.6) & 1.9 (0.1) & 13.0 (0.9) & 1.5 (0.0) & 10.3 (0.5) & 1.6 (0.0) \\
\cline{2-13}
 & \multirow[t]{3}{*}{$\APS$} & $\standard$ & 8.6 (0.5) & 1.7 (0.0) & 8.4 (0.6) & 1.7 (0.0) & 8.4 (0.5) & 1.7 (0.0) & 8.6 (0.5) & 1.7 (0.0) & 7.5 (0.4) & 1.8 (0.0) \\
 &  & $\classwise$ & 5.1 (0.4) & 2.9 (0.1) & 4.0 (0.3) & 2.4 (0.1) & 3.1 (0.4) & 2.2 (0.1) & 2.6 (0.3) & 2.1 (0.1) & 2.7 (0.4) & 2.2 (0.1) \\
 &  & $\clustered$ & 8.9 (1.8) & 1.8 (0.1) & 8.1 (0.8) & 1.7 (0.1) & 5.2 (0.4) & 2.0 (0.1) & 8.6 (0.7) & 1.7 (0.0) & 7.5 (0.5) & 1.8 (0.0) \\
\cline{2-13}
 & \multirow[t]{3}{*}{$\RAPS$} & $\standard$ & 8.7 (0.5) & 1.7 (0.0) & 8.5 (0.5) & 1.7 (0.0) & 8.8 (0.5) & 1.7 (0.0) & 9.1 (0.6) & 1.7 (0.0) & 8.2 (0.4) & 1.7 (0.0) \\
 &  & $\classwise$ & 5.2 (0.3) & 3.0 (0.1) & 4.1 (0.3) & 2.5 (0.1) & 3.1 (0.4) & 2.2 (0.1) & 2.6 (0.4) & 2.2 (0.1) & 2.7 (0.4) & 2.2 (0.1) \\
 &  & $\clustered$ & 9.2 (1.7) & 1.8 (0.1) & 8.6 (0.7) & 1.7 (0.0) & 5.5 (0.4) & 2.0 (0.1) & 8.8 (0.5) & 1.7 (0.0) & 7.9 (0.5) & 1.8 (0.0) \\
\cline{1-13} \cline{2-13}
\bottomrule
\end{tabular}

In [21]:
"""
Add this to your existing notebook/script alongside the table generation code.
This produces a per-seed breakdown for any dataset/score/n/method combination.
"""

import pickle
import numpy as np
import pandas as pd
import glob
import os


def per_seed_results(folder, methods, class_names=None):
    """
    Load all seed pkl files from a folder and return per-seed + averaged results.
    
    Parameters
    ----------
    folder : str
        Path like '.../random_calset/n_totalcal=50/score=APS/'
    methods : dict
        e.g. {'standard': '$\\standard$', 'classwise': '$\\classwise$', ...}
    class_names : list or None
        e.g. ['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative'] for DDR
        If None, uses Class 0, Class 1, ...
    
    Returns
    -------
    df_per_seed : DataFrame with per-seed metrics (CovGap, AvgSize, per-class coverages)
    df_averaged : DataFrame with mean (SE) across seeds
    """
    # Find all seed files
    seed_files = sorted(glob.glob(os.path.join(folder, 'seed=*_allresults.pkl')))
    n_seeds = len(seed_files)
    
    if n_seeds == 0:
        print(f"No seed files found in {folder}")
        return None, None
    
    # Determine number of classes from first file
    with open(seed_files[0], 'rb') as f:
        d = pickle.load(f)
    first_method = list(methods.keys())[0]
    n_classes = len(d[first_method][2]['raw_class_coverages'])
    
    if class_names is None:
        class_names = [f'Class {i}' for i in range(n_classes)]
    
    # Collect per-seed results
    rows = []
    for seed_file in seed_files:
        seed_num = int(os.path.basename(seed_file).split('=')[1].split('_')[0])

        with open(seed_file, 'rb') as f:
            d = pickle.load(f)
        
        for method_key, method_name in methods.items():
            if method_key not in d:
                continue
            t = d[method_key]
            gap = t[2]['mean_class_cov_gap']
            mcov = t[2]['marginal_cov']
            sz = t[3]['mean']
            cov = t[2]['raw_class_coverages']
            
            row = {
                'Seed': seed_num,
                'Method': method_name,
                'CovGap (%)': round(gap * 100, 1),
                'AvgSize': round(sz, 2),
                'MargCov (%)': round(mcov * 100, 1),
            }
            for i, cname in enumerate(class_names):
                row[cname] = round(cov[i] * 100, 1)
            
            rows.append(row)
    
    df_per_seed = pd.DataFrame(rows)
    
    # Compute averaged results with SE
    avg_rows = []
    for method_key, method_name in methods.items():
        method_df = df_per_seed[df_per_seed['Method'] == method_name]
        if len(method_df) == 0:
            continue
        
        row = {'Method': method_name}
        
        for col in ['CovGap (%)', 'AvgSize', 'MargCov (%)'] + class_names:
            vals = method_df[col].values
            mean = np.mean(vals)
            se = np.std(vals) / np.sqrt(len(vals))
            row[col] = f"{mean:.1f} ({se:.1f})"
        
        # Also find best and worst seed
        gaps = method_df['CovGap (%)'].values
        seeds = method_df['Seed'].values
        row['Best Seed'] = f"Seed {seeds[np.argmin(gaps)]} ({np.min(gaps):.1f}%)"
        row['Worst Seed'] = f"Seed {seeds[np.argmax(gaps)]} ({np.max(gaps):.1f}%)"
        
        avg_rows.append(row)
    
    df_averaged = pd.DataFrame(avg_rows)
    
    return df_per_seed, df_averaged


def print_per_seed_summary(folder, methods, class_names=None, title=None):
    """Pretty-print per-seed results."""
    df_per_seed, df_averaged = per_seed_results(folder, methods, class_names)
    
    if df_per_seed is None:
        return
    
    if title:
        print(f"\n{'='*80}")
        print(f" {title}")
        print(f"{'='*80}")
    
    print(f"\n--- Per-Seed Results ---")
    print(df_per_seed.to_string(index=False))
    
    print(f"\n--- Averaged (Mean ± SE) ---")
    print(df_averaged.to_string(index=False))
    
    return df_per_seed, df_averaged


# ============================================================
# USAGE EXAMPLE
# ============================================================

if __name__ == '__main__':
    
    # Define your methods (same as your existing script)
    methods = {
        'standard': 'standard',
        'classwise': 'classwise',
        'exact_coverage_classwise': 'exact_classwise',
        'exact_coverage_cluster': 'clustered',
        'cluster_random': 'cluster_random'
    }
    
    # DDR class names
    ddr_classes = ['No DR', 'Mild', 'Moderate', 'Severe', 'Proliferative']
    
    # DFUC class names (update these to your actual class names)
    dfuc_classes = ['None', 'Infection', 'Ischaemia', 'Both']
    
    # Base path
    base = r'C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n'
    
    # ---- Example: Single config ----
    folder = os.path.join(base, 'ddr', 'ce-ddr', 'random_calset', 'n_totalcal=50', 'score=APS')
    print_per_seed_summary(folder, methods, ddr_classes, title="DDR | CE | n=50 | APS")
    
    folder = os.path.join(base, 'ddr', 'ddr-cp-aware', 'random_calset', 'n_totalcal=50', 'score=APS')
    print_per_seed_summary(folder, methods, ddr_classes, title="DDR | Conformal | n=50 | APS")
    
    # ---- Loop over all configs ----
    datasets = {
        'DDR': {
            'ce': ('ddr', 'ce-ddr', ddr_classes),
            'conf': ('ddr', 'ddr-cp-aware', ddr_classes),
            'focal': ('ddr', 'focal-ddr', ddr_classes),
        },
        'DFUC': {
            'ce': ('dfuc', 'dfuc-ce', dfuc_classes),
            'conf': ('dfuc', 'dfuc-cp-aware', dfuc_classes),
            'focal': ('dfuc', 'focal-dfuc', dfuc_classes),
        },
    }
    scores = ['softmax', 'APS', 'RAPS']
    n_values = [50, 100, 200, 300, 400]
    
    # Collect everything into one big DataFrame
    all_results = []
    for ds_name, losses in datasets.items():
        for loss_name, (ds_dir, loss_dir, cls_names) in losses.items():
            for n in n_values:
                for score in scores:
                    folder = os.path.join(base, ds_dir, loss_dir, 'random_calset', 
                                          f'n_totalcal={n}', f'score={score}')
                    df_per_seed, df_avg = per_seed_results(folder, methods, cls_names)
                    if df_per_seed is not None:
                        df_per_seed['Dataset'] = ds_name
                        df_per_seed['Loss'] = loss_name
                        df_per_seed['n'] = n
                        df_per_seed['Score'] = score
                        all_results.append(df_per_seed)
    
    if all_results:
        df_all = pd.concat(all_results, ignore_index=True)
        
        # Find the best seed for each config
        print("\n\n=== Best seed per config (lowest CovGap) ===")
        idx = df_all.groupby(['Dataset', 'Loss', 'Score', 'n', 'Method'])['CovGap (%)'].idxmin()
        print(df_all.loc[idx][['Dataset', 'Loss', 'Score', 'n', 'Method', 'Seed', 'CovGap (%)']].to_string(index=False))
        
        # Example queries:
        # df_all[(df_all['Dataset']=='DDR') & (df_all['Loss']=='ce') & (df_all['Score']=='APS') & (df_all['n']==50)]
        # df_all[df_all['CovGap (%)'] > 15]  # all configs with gap > 15%

================================================================================
 DDR | CE | n=50 | APS
================================================================================

--- Per-Seed Results ---
 Seed          Method  CovGap (%)  AvgSize  MargCov (%)  No DR  Mild  Moderate  Severe  Proliferative
    0        standard        14.1     1.57         92.8   98.2  53.8      93.4    70.5           86.6
    0       classwise         5.6     3.03         94.8   93.8  97.4      96.3   100.0           90.2
    0 exact_classwise         5.1     2.77         94.6   93.6  97.4      96.3    97.7           90.2
    0       clustered        13.2     1.61         93.0   98.3  56.4      93.5    72.7           86.6
    0  cluster_random        13.3     1.62         93.1   98.4  56.4      93.6    72.7           86.6
    1        standard        19.9     1.35         88.2   95.6  43.5      88.0    55.6           78.9
    1       classwise         6.5     2.57         90.7   91.1  71.3      92.6   100.0           90.4
    1 exact_classwise         5.4     2.25         90.2   91.0  70.4      92.4    88.9           87.3
    1       clustered        22.4     1.25         85.2   93.2  40.0      84.4    51.1           75.9
    1  cluster_random        22.1     1.25         85.4   93.2  40.9      84.5    51.1           76.5
    2        standard        16.8     1.47         90.9   97.2  50.9      90.7    60.0           83.1
    2       classwise         5.1     2.84         90.9   92.8  96.3      86.4   100.0           93.0
    2 exact_classwise         3.9     2.25         90.0   92.5  94.4      85.6    97.5           89.5
    2       clustered        15.8     1.49         91.4   97.7  51.9      91.0    65.0           83.1
    2  cluster_random        15.7     1.50         91.6   97.8  51.9      91.2    65.0           83.7
    3        standard        16.9     1.47         90.9   97.1  46.8      90.9    61.9           84.8
    3       classwise         4.5     2.88         90.7   91.0  89.0      88.5   100.0           98.8
    3 exact_classwise         4.7     2.15         89.0   90.4  80.7      86.2    92.9           97.0
    3       clustered        17.0     1.48         91.0   97.3  46.8      91.0    61.9           84.8
    3  cluster_random        17.0     1.48         91.0   97.3  46.8      91.0    61.9           84.8
    4        standard        19.5     1.34         88.1   95.5  44.2      87.3    56.5           80.1
    4       classwise         5.4     2.86         90.8   91.5  96.5      87.4   100.0           96.3
    4 exact_classwise         2.8     2.55         90.1   91.4  87.6      87.4    91.3           96.3
    4       clustered        19.4     1.34         88.2   95.5  44.2      87.4    56.5           80.1
    4  cluster_random        19.4     1.34         88.2   95.5  44.2      87.4    56.5           80.1

--- Averaged (Mean ± SE) ---
         Method CovGap (%)   AvgSize MargCov (%)      No DR       Mild   Moderate      Severe Proliferative      Best Seed     Worst Seed
       standard 17.4 (0.9) 1.4 (0.0)  90.2 (0.8) 96.7 (0.5) 47.8 (1.8) 90.1 (1.0)  60.9 (2.4)    82.7 (1.3) Seed 0 (14.1%) Seed 1 (19.9%)
      classwise  5.4 (0.3) 2.8 (0.1)  91.6 (0.7) 92.0 (0.5) 90.1 (4.4) 90.2 (1.7) 100.0 (0.0)    93.7 (1.5)  Seed 3 (4.5%)  Seed 1 (6.5%)
exact_classwise  4.4 (0.4) 2.4 (0.1)  90.8 (0.9) 91.8 (0.5) 86.1 (4.4) 89.6 (1.8)  93.7 (1.5)    92.1 (1.7)  Seed 4 (2.8%)  Seed 1 (5.4%)
      clustered 17.6 (1.4) 1.4 (0.1)  89.8 (1.2) 96.4 (0.8) 47.9 (2.6) 89.5 (1.4)  61.4 (3.3)    82.1 (1.7) Seed 0 (13.2%) Seed 1 (22.4%)
 cluster_random 17.5 (1.4) 1.4 (0.1)  89.9 (1.2) 96.4 (0.8) 48.0 (2.5) 89.5 (1.4)  61.4 (3.3)    82.3 (1.6) Seed 0 (13.3%) Seed 1 (22.1%)

================================================================================
 DDR | Conformal | n=50 | APS
================================================================================

--- Per-Seed Results ---
 Seed          Method  CovGap (%)  AvgSize  MargCov (%)  No DR  Mild  Moderate  Severe  Proliferative
    0        standard         2.7     2.31         92.3   91.0  85.5      95.3    90.9           91.5
    0       classwise         4.5     3.33         92.6   90.0  90.6      95.3   100.0           96.3
    0 exact_classwise         3.6     2.97         92.3   89.6  90.6      95.3    95.5           96.3
    0       clustered         3.0     2.46         93.5   92.6  87.2      96.0    90.9           92.7
    0  cluster_random         3.4     2.48         93.8   92.9  88.0      96.2    93.2           92.7
    1        standard         3.0     2.16         90.1   88.6  83.5      93.7    88.9           88.0
    1       classwise         4.4     3.22         89.8   88.4  87.8      89.7   100.0           98.2
    1 exact_classwise         1.9     2.83         89.1   88.4  87.8      89.7    86.7           92.2
    1       clustered         4.3     2.07         88.4   87.2  80.9      92.1    88.9           83.7
    1  cluster_random         4.3     2.07         88.5   87.4  80.9      92.2    88.9           83.7
    2        standard         3.5     2.29         92.2   91.2  84.3      94.7    95.0           90.7
    2       classwise         6.0     3.66         92.2   92.6  97.2      89.2   100.0           99.4
    2 exact_classwise         5.5     3.29         91.9   92.6  97.2      88.8   100.0           96.5
    2       clustered         3.5     2.29         92.2   91.2  84.3      94.7    95.0           90.7
    2  cluster_random         3.5     2.29         92.2   91.2  84.3      94.7    95.0           90.7
    3        standard         2.8     2.20         90.9   89.6  83.5      93.8    92.9           90.3
    3       classwise         5.5     3.47         91.8   89.1  94.5      93.4   100.0           98.8
    3 exact_classwise         4.6     2.86         91.4   88.9  94.5      92.8    97.6           97.0
    3       clustered         3.1     2.18         90.6   89.0  82.6      93.8    92.9           90.3
    3  cluster_random         2.9     2.19         90.7   89.1  83.5      93.8    92.9           90.3
    4        standard         2.2     2.26         91.7   90.6  85.8      94.1    91.3           90.7
    4       classwise         5.3     3.46         91.8   90.8  99.1      90.9   100.0           95.7
    4 exact_classwise         6.9     3.21         90.6   90.8  99.1      89.2    71.7           95.7
    4       clustered         2.2     2.25         91.7   90.6  85.8      94.1    91.3           90.7
    4  cluster_random         2.2     2.26         91.7   90.6  85.8      94.1    91.3           90.7

--- Averaged (Mean ± SE) ---
         Method CovGap (%)   AvgSize MargCov (%)      No DR       Mild   Moderate      Severe Proliferative     Best Seed    Worst Seed
       standard  2.8 (0.2) 2.2 (0.0)  91.4 (0.4) 90.2 (0.4) 84.5 (0.4) 94.3 (0.3)  91.8 (0.9)    90.2 (0.5) Seed 4 (2.2%) Seed 2 (3.5%)
      classwise  5.1 (0.3) 3.4 (0.1)  91.6 (0.4) 90.2 (0.7) 93.8 (1.9) 91.7 (1.0) 100.0 (0.0)    97.7 (0.6) Seed 1 (4.4%) Seed 2 (6.0%)
exact_classwise  4.5 (0.8) 3.0 (0.1)  91.1 (0.5) 90.1 (0.7) 93.8 (1.9) 91.2 (1.1)  90.3 (4.6)    95.5 (0.8) Seed 1 (1.9%) Seed 4 (6.9%)
      clustered  3.2 (0.3) 2.2 (0.1)  91.3 (0.8) 90.1 (0.8) 84.2 (1.0) 94.1 (0.6)  91.8 (0.9)    89.6 (1.4) Seed 4 (2.2%) Seed 1 (4.3%)
 cluster_random  3.3 (0.3) 2.3 (0.1)  91.4 (0.8) 90.2 (0.8) 84.5 (1.1) 94.2 (0.6)  92.3 (0.9)    89.6 (1.4) Seed 4 (2.2%) Seed 1 (4.3%)
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=50\score=softmax
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=50\score=APS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=50\score=RAPS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=100\score=softmax
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=100\score=APS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=100\score=RAPS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=200\score=softmax
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=200\score=APS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=200\score=RAPS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=300\score=softmax
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=300\score=APS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=300\score=RAPS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=400\score=softmax
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=400\score=APS
No seed files found in C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\dfuc\focal-dfuc\random_calset\n_totalcal=400\score=RAPS


=== Best seed per config (lowest CovGap) ===
Dataset  Loss   Score   n          Method  Seed  CovGap (%)
    DDR    ce     APS  50       classwise     3         4.5
    DDR    ce     APS  50  cluster_random     0        13.3
    DDR    ce     APS  50       clustered     0        13.2
    DDR    ce     APS  50 exact_classwise     4         2.8
    DDR    ce     APS  50        standard     0        14.1
    DDR    ce     APS 100       classwise     3         3.3
    DDR    ce     APS 100  cluster_random     2        10.4
    DDR    ce     APS 100       clustered     2        10.4
    DDR    ce     APS 100 exact_classwise     4         1.8
    DDR    ce     APS 100        standard     3        15.3
    DDR    ce     APS 200       classwise     1         2.7
    DDR    ce     APS 200  cluster_random     3         7.1
    DDR    ce     APS 200       clustered     3         7.9
    DDR    ce     APS 200 exact_classwise     2         2.3
    DDR    ce     APS 200        standard     3        15.9
    DDR    ce     APS 300       classwise     1         2.3
    DDR    ce     APS 300  cluster_random     2         2.5
    DDR    ce     APS 300       clustered     1         2.6
    DDR    ce     APS 300 exact_classwise     1         1.3
    DDR    ce     APS 300        standard     3        13.7
    DDR    ce     APS 400       classwise     2         1.4
    DDR    ce     APS 400  cluster_random     4         2.0
    DDR    ce     APS 400       clustered     4         2.0
    DDR    ce     APS 400 exact_classwise     4         1.3
    DDR    ce     APS 400        standard     3        11.4
    DDR    ce    RAPS  50       classwise     1         3.3
    DDR    ce    RAPS  50  cluster_random     0        14.4
    DDR    ce    RAPS  50       clustered     0        14.5
    DDR    ce    RAPS  50 exact_classwise     4         2.6
    DDR    ce    RAPS  50        standard     0        14.9
    DDR    ce    RAPS 100       classwise     0         2.1
    DDR    ce    RAPS 100  cluster_random     4         9.8
    DDR    ce    RAPS 100       clustered     4         9.8
    DDR    ce    RAPS 100 exact_classwise     4         2.2
    DDR    ce    RAPS 100        standard     3        16.3
    DDR    ce    RAPS 200       classwise     3         1.7
    DDR    ce    RAPS 200  cluster_random     3         7.7
    DDR    ce    RAPS 200       clustered     3         8.2
    DDR    ce    RAPS 200 exact_classwise     2         1.3
    DDR    ce    RAPS 200        standard     3        16.0
    DDR    ce    RAPS 300       classwise     2         2.2
    DDR    ce    RAPS 300  cluster_random     2         2.3
    DDR    ce    RAPS 300       clustered     2         2.4
    DDR    ce    RAPS 300 exact_classwise     4         2.1
    DDR    ce    RAPS 300        standard     3        14.0
    DDR    ce    RAPS 400       classwise     4         0.7
    DDR    ce    RAPS 400  cluster_random     4         2.0
    DDR    ce    RAPS 400       clustered     4         2.3
    DDR    ce    RAPS 400 exact_classwise     4         1.1
    DDR    ce    RAPS 400        standard     3        11.7
    DDR    ce softmax  50       classwise     2         4.6
    DDR    ce softmax  50  cluster_random     0        16.3
    DDR    ce softmax  50       clustered     0        16.5
    DDR    ce softmax  50 exact_classwise     2         1.2
    DDR    ce softmax  50        standard     0        18.7
    DDR    ce softmax 100       classwise     0         4.0
    DDR    ce softmax 100  cluster_random     4        10.9
    DDR    ce softmax 100       clustered     4        11.3
    DDR    ce softmax 100 exact_classwise     4         2.3
    DDR    ce softmax 100        standard     3        18.4
    DDR    ce softmax 200       classwise     2         2.7
    DDR    ce softmax 200  cluster_random     4         9.3
    DDR    ce softmax 200       clustered     4         8.8
    DDR    ce softmax 200 exact_classwise     4         3.1
    DDR    ce softmax 200        standard     3        18.1
    DDR    ce softmax 300       classwise     1         0.8
    DDR    ce softmax 300  cluster_random     4         2.4
    DDR    ce softmax 300       clustered     4         2.4
    DDR    ce softmax 300 exact_classwise     1         0.8
    DDR    ce softmax 300        standard     3        17.3
    DDR    ce softmax 400       classwise     2         2.0
    DDR    ce softmax 400  cluster_random     4         2.7
    DDR    ce softmax 400       clustered     4         3.9
    DDR    ce softmax 400 exact_classwise     2         2.0
    DDR    ce softmax 400        standard     3        15.4
    DDR  conf     APS  50       classwise     1         4.4
    DDR  conf     APS  50  cluster_random     4         2.2
    DDR  conf     APS  50       clustered     4         2.2
    DDR  conf     APS  50 exact_classwise     1         1.9
    DDR  conf     APS  50        standard     4         2.2
    DDR  conf     APS 100       classwise     0         2.4
    DDR  conf     APS 100  cluster_random     3         2.4
    DDR  conf     APS 100       clustered     3         3.0
    DDR  conf     APS 100 exact_classwise     0         1.9
    DDR  conf     APS 100        standard     3         2.4
    DDR  conf     APS 200       classwise     1         1.9
    DDR  conf     APS 200  cluster_random     1         1.9
    DDR  conf     APS 200       clustered     1         1.9
    DDR  conf     APS 200 exact_classwise     1         1.5
    DDR  conf     APS 200        standard     2         1.8
    DDR  conf     APS 300       classwise     2         2.5
    DDR  conf     APS 300  cluster_random     4         2.2
    DDR  conf     APS 300       clustered     0         2.3
    DDR  conf     APS 300 exact_classwise     2         2.3
    DDR  conf     APS 300        standard     2         2.8
    DDR  conf     APS 400       classwise     4         2.2
    DDR  conf     APS 400  cluster_random     2         1.6
    DDR  conf     APS 400       clustered     2         1.6
    DDR  conf     APS 400 exact_classwise     2         2.3
    DDR  conf     APS 400        standard     2         1.2
    DDR  conf    RAPS  50       classwise     1         4.3
    DDR  conf    RAPS  50  cluster_random     4         2.5
    DDR  conf    RAPS  50       clustered     4         2.5
    DDR  conf    RAPS  50 exact_classwise     1         1.6
    DDR  conf    RAPS  50        standard     4         2.5
    DDR  conf    RAPS 100       classwise     3         2.4
    DDR  conf    RAPS 100  cluster_random     3         2.3
    DDR  conf    RAPS 100       clustered     3         2.6
    DDR  conf    RAPS 100 exact_classwise     3         2.4
    DDR  conf    RAPS 100        standard     3         2.3
    DDR  conf    RAPS 200       classwise     0         2.2
    DDR  conf    RAPS 200  cluster_random     1         1.9
    DDR  conf    RAPS 200       clustered     1         1.9
    DDR  conf    RAPS 200 exact_classwise     1         1.6
    DDR  conf    RAPS 200        standard     2         1.9
    DDR  conf    RAPS 300       classwise     2         2.6
    DDR  conf    RAPS 300  cluster_random     0         2.0
    DDR  conf    RAPS 300       clustered     0         2.0
    DDR  conf    RAPS 300 exact_classwise     2         2.4
    DDR  conf    RAPS 300        standard     2         2.5
    DDR  conf    RAPS 400       classwise     4         2.2
    DDR  conf    RAPS 400  cluster_random     2         1.4
    DDR  conf    RAPS 400       clustered     2         1.4
    DDR  conf    RAPS 400 exact_classwise     4         2.2
    DDR  conf    RAPS 400        standard     2         1.8
    DDR  conf softmax  50       classwise     3         4.5
    DDR  conf softmax  50  cluster_random     0         3.4
    DDR  conf softmax  50       clustered     0         3.4
    DDR  conf softmax  50 exact_classwise     4         2.7
    DDR  conf softmax  50        standard     0         3.4
    DDR  conf softmax 100       classwise     0         3.1
    DDR  conf softmax 100  cluster_random     3         3.7
    DDR  conf softmax 100       clustered     3         3.8
    DDR  conf softmax 100 exact_classwise     0         1.2
    DDR  conf softmax 100        standard     3         3.7
    DDR  conf softmax 200       classwise     0         1.1
    DDR  conf softmax 200  cluster_random     0         3.8
    DDR  conf softmax 200       clustered     0         3.8
    DDR  conf softmax 200 exact_classwise     0         1.3
    DDR  conf softmax 200        standard     4         4.3
    DDR  conf softmax 300       classwise     4         2.4
    DDR  conf softmax 300  cluster_random     3         2.3
    DDR  conf softmax 300       clustered     3         2.4
    DDR  conf softmax 300 exact_classwise     4         2.4
    DDR  conf softmax 300        standard     3         6.4
    DDR  conf softmax 400       classwise     4         1.6
    DDR  conf softmax 400  cluster_random     3         2.3
    DDR  conf softmax 400       clustered     3         2.4
    DDR  conf softmax 400 exact_classwise     3         2.0
    DDR  conf softmax 400        standard     3         6.1
    DDR focal     APS  50       classwise     4         4.5
    DDR focal     APS  50  cluster_random     3         7.3
    DDR focal     APS  50       clustered     3         7.3
    DDR focal     APS  50 exact_classwise     4         3.2
    DDR focal     APS  50        standard     3         9.8
    DDR focal     APS 100       classwise     4         2.8
    DDR focal     APS 100  cluster_random     4         3.8
    DDR focal     APS 100       clustered     4         4.2
    DDR focal     APS 100 exact_classwise     4         2.0
    DDR focal     APS 100        standard     3        10.8
    DDR focal     APS 200       classwise     2         2.8
    DDR focal     APS 200  cluster_random     3         4.8
    DDR focal     APS 200       clustered     3         4.8
    DDR focal     APS 200 exact_classwise     4         3.7
    DDR focal     APS 200        standard     4        10.5
    DDR focal     APS 300       classwise     1         2.6

In [ ]:
import os

folder = r'C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\ddr\ce-ddr\random_calset\n_totalcal=50\score=APS'

print(f"Folder exists: {os.path.exists(folder)}")
print(f"Contents: {os.listdir(folder)}")

Folder exists: True
Contents: ['seed=0_allresults.pkl', 'seed=1_allresults.pkl', 'seed=2_allresults.pkl', 'seed=3_allresults.pkl', 'seed=4_allresults.pkl']

## Additonal tables
Unused in paper

In [ ]:
# # Investigate marginal coverage

# n_totalcals = {10: '$n_{\text{avg}}=10$', 
#                20: '$n_{\text{avg}}=20$', 
#                30: '$n_{\text{avg}}=30$', 
#                40: '$n_{\text{avg}}=40$', 
#                50: '$n_{\text{avg}}=50$', 
#                75: '$n_{\text{avg}}=75$',
#                100: '$n_{\text{avg}}=100$'}

# methods = {'standard': '$\standard$', 
#             'classwise': '$\classwise$',
#             'exact_coverage_classwise': 'ExactCov-$\classwise$',
#             'cluster_random': '$\clustered$',
#             'exact_coverage_cluster': 'ExactCov-$\clustered$'} 

# horizontal_dict = {}
# for n_totalcal, n_name in n_totalcals.items():
#     vertical_list = []
#     for dataset, save_folder in datasets.items():
#         for score, score_name in score_functions.items():
#             for method, method_name in methods.items(): 

#                 folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
#                 print(folder)
#                 df = average_results_across_seeds(folder, print_results=False, display_table=False, methods=methods.keys()) # df = results DataFrame
#                 s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                               'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
#                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
#                 vertical_list.append(pd.DataFrame(s).transpose())                                        

#     df = pd.concat(vertical_list, ignore_index=True)                                                     
#     df = df.set_index(['Dataset', 'Score func.', 'Method'])
#     horizontal_dict[n_name] = df

# df = pd.concat(horizontal_dict, axis=1)
# df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
#     escape=False # So that backslashes are printed as `\' rather than '\textbackslash'
#                  )
# # Post-process
# # df_str = df_str.replace('lllllllll', 'lllcrccrc')
# # df_str = df_str.replace('$n_{\\text{avg}}=75$ \\',
# #                '$n_{\\text{avg}}=75$ \\\\ \cmidrule(lr){4}\cmidrule(lr){5} \cmidrule(lr){6}\\')
# df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
# df_str = df_str.replace('Places365', '\midrule\nPlaces365')
# df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# print(df_str)

In [ ]:
# df

Additionally include results for randomized methods

In [ ]:
# methods = {'standard': '$\standard$', 
#             'exact_coverage_standard': 'Randomized $\standard$',
#             'classwise': '$\classwise$',
#             'exact_coverage_classwise': 'Randomized $\classwise$',
#             'cluster_random': '$\clustered$',
#             'exact_coverage_cluster': 'Randomized $\clustered$'}

In [ ]:
# n_totalcals = {10: '$n_{\text{avg}}=10$', 20: '$n_{\text{avg}}=20$', 
#                50: '$n_{\text{avg}}=50$', 75: '$n_{\text{avg}}=75$'}

# datasets = {'ImageNet': '../.cache/paper/varying_n/imagenet',
#             'CIFAR-100': '../.cache/paper/varying_n/cifar-100',
#             'Places365': '../.cache/paper/varying_n/places365',
#             'iNaturalist': '../.cache/paper/varying_n/inaturalist'}

# horizontal_dict = {}
# for n_totalcal, n_name in n_totalcals.items():
#     vertical_list = []
#     for dataset, save_folder in datasets.items():
#         for score, score_name in score_functions.items():
#             for method, method_name in methods.items(): 

#                 folder = f'{save_folder}/{calibration_sampling}_calset/n_totalcal={n_totalcal}/score={score}/'
#                 print(folder)
#                 df = average_results_across_seeds(folder, print_results=False, display_table=False,methods=methods.keys()) # df = results DataFrame
#                 s = pd.Series({'Dataset': dataset, 'Score func.': score_name, 'Method': method_name, 
#                                'CovGap': f"{df[df['method'] == method]['class_cov_gap_mean'].values[0]:.1f}" 
#                                        f" ({df[df['method'] == method]['class_cov_gap_se'].values[0]:.1f})",
#                                'AvgSize': f"{df[df['method'] == method]['avg_set_size_mean'].values[0]:.1f}" 
#                                                f" ({df[df['method'] == method]['avg_set_size_se'].values[0]:.1f})"})
# #                                'MargCov': f"{df[df['method'] == method]['marginal_cov_mean'].values[0]*100:.1f}" 
# #                                                    f" ({df[df['method'] == method]['marginal_cov_se'].values[0]*100:.1f})"})
#                 vertical_list.append(pd.DataFrame(s).transpose())                                        

#     df = pd.concat(vertical_list, ignore_index=True)                                                     
#     df = df.set_index(['Dataset', 'Score func.', 'Method'])
#     horizontal_dict[n_name] = df

# df = pd.concat(horizontal_dict, axis=1)
# df_str = df.to_latex(multicolumn_format='c', # To center multilevel column headers
#     escape=False) # So that backslashes are printed as `\' rather than '\textbackslash'
                 
# # Post-process
# df_str = df_str.replace('lllllllllll', 'lllcrcrcrcr')
# df_str = df_str.replace('\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\',
#                '\\multicolumn{2}{c}{$n_{\\text{avg}}=75$} \\\\ \cmidrule(lr){4-5}\cmidrule(lr){6-7} \cmidrule(lr){8-9} \cmidrule(lr){10-11}\\')
# df_str = df_str.replace('CIFAR-100', '\midrule\nCIFAR-100')
# df_str = df_str.replace('Places365', '\midrule\nPlaces365')
# df_str = df_str.replace('iNaturalist', '\midrule\niNaturalist')
# # Add horizontal lines between methods
# df_str = df_str.replace('& $\APS$', '\cline{3-11} & $\APS$')
# df_str = df_str.replace('& $\RAPS$', '\cline{3-11} & $\RAPS$')
# print(df_str)

In [ ]:
# pd.set_option('display.max_rows', None) # Show all rows
# df

In [ ]:
import os
import pickle
import pandas as pd
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────
BASE_DIR = Path(
    r"C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\ddr\focal-ddr\random_calset"
)
N_TOTALCALS = [50, 100, 200, 300, 400, 500]
SCORES = ["APS", "softmax", "RAPS"]
OUTPUT_CSV = Path(BASE_DIR) / "all_seed_results.csv"

# ── Collect results ────────────────────────────────────────────────────────
rows = []

for n in N_TOTALCALS:
    for score in SCORES:
        score_dir = BASE_DIR / f"n_totalcal={n}" / f"score={score}"

        if not score_dir.exists():
            print(f"[WARN] Directory not found: {score_dir}")
            continue

        # Find all pkl files in this directory (and subdirs if any)
        pkl_files = sorted(score_dir.glob("**/*.pkl"))

        if not pkl_files:
            print(f"[WARN] No .pkl files in {score_dir}")
            continue

        for pkl_path in pkl_files:
            try:
                with open(pkl_path, "rb") as f:
                    data = pickle.load(f)
            except Exception as e:
                print(f"[ERROR] Could not read {pkl_path}: {e}")
                continue

            # --- Adapt this section to your pkl structure ---
            # If data is a dict, flatten it into the row
            if isinstance(data, dict):
                row = {
                    "n_totalcal": n,
                    "score": score,
                    "file": pkl_path.name,
                }
                row.update(data)
                rows.append(row)

            # If data is a list of dicts (one per seed), iterate
            elif isinstance(data, list):
                for item in data:
                    row = {
                        "n_totalcal": n,
                        "score": score,
                        "file": pkl_path.name,
                    }
                    if isinstance(item, dict):
                        row.update(item)
                    else:
                        row["value"] = item
                    rows.append(row)

            # Fallback: store raw value
            else:
                rows.append({
                    "n_totalcal": n,
                    "score": score,
                    "file": pkl_path.name,
                    "value": data,
                })

# ── Export ──────────────────────────────────────────────────────────────────
df = pd.DataFrame(rows)
df.to_csv(OUTPUT_CSV, index=False)
print(f"\nSaved {len(df)} rows to {OUTPUT_CSV}")
print(df.head(10).to_string())

Saved 90 rows to C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\ddr\focal-ddr\random_calset\all_seed_results.csv
   n_totalcal    score                   file                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      standard                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           classwise                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             exact_coverage_classwise                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             exact_coverage_cluster                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          cluster_proportional                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             cluster_doubledip                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cluster_random
0          50      APS  seed=0_allresults.pkl  (0.9207149420688787, None, {'mean_class_cov_gap': 0.11939340049139428, 'undercov_gap': 0.17471873203580524, 'overcov_gap': 0.03640540317477786, 'max_gap': 0.34444444444444444, 'very_undercovered': 0.4, 'marginal_cov': 0.9117516629711752, 'raw_class_coverages': [0.9721973094170404, 0.5555555555555556, 0.9006134969325154, 0.7727272727272727, 0.8475609756097561], 'cluster_assignments': None}, {'mean': 1.5951219512195123, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})      ([0.8151830717003841, 0.9878948220476328, 0.9663468949765194, inf, 0.9622053799438129], None, {'mean_class_cov_gap': 0.0555238893754799, 'undercov_gap': 0.05439337085678553, 'overcov_gap': 0.05627756838794281, 'max_gap': 0.1051282051282052, 'very_undercovered': 0.2, 'marginal_cov': 0.9228381374722838, 'raw_class_coverages': [0.9130044843049328, 0.7948717948717948, 0.9558282208588957, 1.0, 0.8963414634146342], 'cluster_assignments': None}, {'mean': 2.8811529933481155, '[.25, .5, .75, .9] quantiles': [2.0, 3.0, 3.0, 4.0]})                                                 ({'q_a': [0.8151830717003841, 0.9878948220476328, 0.9663468949765194, inf, 0.9622053799438129], 'q_b': [0.803519258842433, 0.9460376670154218, 0.9642627038629971, 0.976845311942859, 0.9281849451250831], 'gamma': [0.10000000000000772, 1.0, 0.8, 0.6000000000000001, 1.0]}, None, {'mean_class_cov_gap': 0.03991443156871266, 'undercov_gap': 0.05439337085678553, 'overcov_gap': 0.03026180537666408, 'max_gap': 0.1051282051282052, 'very_undercovered': 0.2, 'marginal_cov': 0.916629711751663, 'raw_class_coverages': [0.9031390134529148, 0.7948717948717948, 0.9558282208588957, 0.9318181818181818, 0.8963414634146342], 'cluster_assignments': None}, {'mean': 2.5148558758314854, '[.25, .5, .75, .9] quantiles': [2.0, 3.0, 3.0, 4.0]})     ({'q_a': [0.9260288922483205, 0.9260288922483205, 0.9260288922483205, 0.9260288922483205, 0.9260288922483205], 'q_b': [0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787], 'gamma': [0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962]}, None, {'mean_class_cov_gap': 0.11552559735917015, 'undercov_gap': 0.1651104541348444, 'overcov_gap': 0.04114831219565873, 'max_gap': 0.34444444444444444, 'very_undercovered': 0.4, 'marginal_cov': 0.9161862527716186, 'raw_class_coverages': [0.9730941704035875, 0.5555555555555556, 0.90920245398773, 0.7954545454545454, 0.8536585365853658], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.6177383592017738, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})  ([0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787], None, {'mean_class_cov_gap': 0.11939340049139428, 'undercov_gap': 0.17471873203580524, 'overcov_gap': 0.03640540317477786, 'max_gap': 0.34444444444444444, 'very_undercovered': 0.4, 'marginal_cov': 0.9117516629711752, 'raw_class_coverages': [0.9721973094170404, 0.5555555555555556, 0.9006134969325154, 0.7727272727272727, 0.8475609756097561], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 5}, {'mean': 1.5951219512195123, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})  ([0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787, 0.9207149420688787], None, {'mean_class_cov_gap': 0.11939340049139428, 'undercov_gap': 0.17471873203580524, 'overcov_gap': 0.03640540317477786, 'max_gap': 0.34444444444444444, 'very_undercovered': 0.4, 'marginal_cov': 0.9117516629711752, 'raw_class_coverages': [0.9721973094170404, 0.5555555555555556, 0.9006134969325154, 0.7727272727272727, 0.8475609756097561], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 1}, {'mean': 1.5951219512195123, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})     ([0.9260288922483205, 0.9260288922483205, 0.9260288922483205, 0.9260288922483205, 0.9260288922483205], None, {'mean_class_cov_gap': 0.11552559735917015, 'undercov_gap': 0.1651104541348444, 'overcov_gap': 0.04114831219565873, 'max_gap': 0.34444444444444444, 'very_undercovered': 0.4, 'marginal_cov': 0.9161862527716186, 'raw_class_coverages': [0.9730941704035875, 0.5555555555555556, 0.90920245398773, 0.7954545454545454, 0.8536585365853658], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.6226164079822616, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})
1          50      APS  seed=1_allresults.pkl     (0.8699215847506718, None, {'mean_class_cov_gap': 0.1802245521808087, 'undercov_gap': 0.21319253350294767, 'overcov_gap': 0.04835262689225284, 'max_gap': 0.4043478260869565, 'very_undercovered': 0.6, 'marginal_cov': 0.8643015521064301, 'raw_class_coverages': [0.9483526268922529, 0.4956521739130435, 0.8300248138957816, 0.6444444444444445, 0.7771084337349398], 'cluster_assignments': None}, {'mean': 1.353880266075388, '[.25, .5, .75, .9] quantiles': [1.0, 1.0, 2.0, 2.0]})  ([0.7981895281881342, 0.9973327101168016, 0.8770919363082508, inf, 0.9756029909263029], None, {'mean_class_cov_gap': 0.05015173036581526, 'undercov_gap': 0.034598812556759284, 'overcov_gap': 0.060520342238519244, 'max_gap': 0.09999999999999998, 'very_undercovered': 0.0, 'marginal_cov': 0.8815964523281596, 'raw_class_coverages': [0.8958147818343722, 0.9478260869565217, 0.8349875930521092, 1.0, 0.9337349397590361], 'cluster_assignments': None}, {'mean': 2.8226164079822618, '[.25, .5, .75, .9] quantiles': [2.0, 3.0, 3.0, 4.0]})  ({'q_a': [0.7981895281881342, 0.9973327101168016, 0.8770919363082508, inf, 0.9756029909263029], 'q_b': [0.7724953261015831, 0.9957051297477804, 0.8707018422042486, 0.7588782125829401, 0.9663915317419356], 'gamma': [0.9000000000000087, 0.8000000000000005, 0.900000000000001, 0.7000000000000001, 0.2000000000000012]}, None, {'mean_class_cov_gap': 0.03590925321081848, 'undercov_gap': 0.04158439355635805, 'overcov_gap': 0.02739654269250913, 'max_gap': 0.06501240694789079, 'very_undercovered': 0.0, 'marginal_cov': 0.8767184035476718, 'raw_class_coverages': [0.8958147818343722, 0.9391304347826087, 0.8349875930521092, 0.8444444444444444, 0.9156626506024096], 'cluster_assignments': None}, {'mean': 2.5175166297117517, '[.25, .5, .75, .9] quantiles': [2.0, 3.0, 3.0, 4.0]})     ({'q_a': [0.8692745586212065, 0.8692745586212065, 0.8692745586212065, 0.8692745586212065, 0.8692745586212065], 'q_b': [0.864743327117115, 0.864743327117115, 0.864743327117115, 0.864743327117115, 0.864743327117115], 'gamma': [0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962]}, None, {'mean_class_cov_gap': 0.18160749383553793, 'undercov_gap': 0.21536644654642595, 'overcov_gap': 0.046571682991985774, 'max_gap': 0.41304347826086957, 'very_undercovered': 0.6, 'marginal_cov': 0.8629711751662971, 'raw_class_coverages': [0.9465716829919858, 0.48695652173913045, 0.8300248138957816, 0.6444444444444445, 0.7771084337349398], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.3467849223946784, '[.25, .5, .75, .9] quantiles': [1.0, 1.0, 2.0, 2.0]})     ([0.8699215847506718, 0.8699215847506718, 0.8699215847506718, 0.8699215847506718, 0.8699215847506718], None, {'mean_class_cov_gap': 0.1802245521808087, 'undercov_gap': 0.21319253350294767, 'overcov_gap': 0.04835262689225284, 'max_gap': 0.4043478260869565, 'very_undercovered': 0.6, 'marginal_cov': 0.8643015521064301, 'raw_class_coverages': [0.9483526268922529, 0.4956521739130435, 0.8300248138957816, 0.6444444444444445, 0.7771084337349398], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 5}, {'mean': 1.353880266075388, '[.25, .5, .75, .9] quantiles': [1.0, 1.0, 2.0, 2.0]})     ([0.8699215847506718, 0.8699215847506718, 0.8699215847506718, 0.8699215847506718, 0.8699215847506718], None, {'mean_class_cov_gap': 0.1802245521808087, 'undercov_gap': 0.21319253350294767, 'overcov_gap': 0.04835262689225284, 'max_gap': 0.4043478260869565, 'very_undercovered': 0.6, 'marginal_cov': 0.8643015521064301, 'raw_class_coverages': [0.9483526268922529, 0.4956521739130435, 0.8300248138957816, 0.6444444444444445, 0.7771084337349398], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 1}, {'mean': 1.353880266075388, '[.25, .5, .75, .9] quantiles': [1.0, 1.0, 2.0, 2.0]})  ([0.8692745586212065, 0.8692745586212065, 0.8692745586212065, 0.8692745586212065, 0.8692745586212065], None, {'mean_class_cov_gap': 0.18178558822556462, 'undercov_gap': 0.21536644654642595, 'overcov_gap': 0.04746215494211925, 'max_gap': 0.41304347826086957, 'very_undercovered': 0.6, 'marginal_cov': 0.8634146341463415, 'raw_class_coverages': [0.9474621549421193, 0.48695652173913045, 0.8300248138957816, 0.6444444444444445, 0.7771084337349398], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.351219512195122, '[.25, .5, .75, .9] quantiles': [1.0, 1.0, 2.0, 2.0]})
2          50      APS  seed=2_allresults.pkl                (0.9415995360952689, None, {'mean_class_cov_gap': 0.10425135220135757, 'undercov_gap': 0.13915446454206146, 'overcov_gap': 0.05189668369030176, 'max_gap': 0.27037037037037037, 'very_undercovered': 0.4, 'marginal_cov': 0.9317073170731708, 'raw_class_coverages': [0.9796640141467727, 0.6296296296296297, 0.9241293532338308, 0.775, 0.877906976744186], 'cluster_assignments': None}, {'mean': 1.7228381374722839, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 3.0]})                     ([0.8163612906428569, 0.9994363794548207, 0.9543154584874847, inf, 0.9985631713849609], None, {'mean_class_cov_gap': 0.06522205489458237, 'undercov_gap': nan, 'overcov_gap': 0.06522205489458237, 'max_gap': 0.09999999999999998, 'very_undercovered': 0.0, 'marginal_cov': 0.9330376940133037, 'raw_class_coverages': [0.9151193633952255, 0.9814814814814815, 0.9353233830845771, 1.0, 0.9941860465116279], 'cluster_assignments': None}, {'mean': 3.426607538802661, '[.25, .5, .75, .9] quantiles': [3.0, 3.0, 4.0, 4.0]})             ({'q_a': [0.8163612906428569, 0.9994363794548207, 0.9543154584874847, inf, 0.9985631713849609], 'q_b': [0.8139563864248224, 0.9984280287863687, 0.9523805941419883, 0.7251587863216352, 0.8903011177483966], 'gamma': [0.7000000000000014, 0.10000000000000042, 0.7000000000000042, 0.20000000000000018, 0.8000000000000005]}, None, {'mean_class_cov_gap': 0.09574289465359376, 'undercov_gap': 0.30000000000000004, 'overcov_gap': 0.044678618316992186, 'max_gap': 0.30000000000000004, 'very_undercovered': 0.2, 'marginal_cov': 0.9219512195121952, 'raw_class_coverages': [0.9142351900972591, 0.9814814814814815, 0.9353233830845771, 0.6, 0.9476744186046512], 'cluster_assignments': None}, {'mean': 2.4957871396895785, '[.25, .5, .75, .9] quantiles': [2.0, 3.0, 3.0, 4.0]})                     ({'q_a': [0.9296083674210072, 0.9296083674210072, 0.9296083674210072, 0.9296083674210072, 0.9296083674210072], 'q_b': [0.913371786446292, 0.913371786446292, 0.913371786446292, 0.913371786446292, 0.913371786446292], 'gamma': [0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962, 0.7999999999999962]}, None, {'mean_class_cov_gap': 0.12312066679126728, 'undercov_gap': 0.17900516795865637, 'overcov_gap': 0.03929391504018365, 'max_gap': 0.31666666666666665, 'very_undercovered': 0.4, 'marginal_cov': 0.9170731707317074, 'raw_class_coverages': [0.9743589743589743, 0.5833333333333334, 0.904228855721393, 0.725, 0.8546511627906976], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.6181818181818182, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})                ([0.9415995360952689, 0.9415995360952689, 0.9415995360952689, 0.9415995360952689, 0.9415995360952689], None, {'mean_class_cov_gap': 0.10425135220135757, 'undercov_gap': 0.13915446454206146, 'overcov_gap': 0.05189668369030176, 'max_gap': 0.27037037037037037, 'very_undercovered': 0.4, 'marginal_cov': 0.9317073170731708, 'raw_class_coverages': [0.9796640141467727, 0.6296296296296297, 0.9241293532338308, 0.775, 0.877906976744186], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 5}, {'mean': 1.7228381374722839, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 3.0]})                ([0.9415995360952689, 0.9415995360952689, 0.9415995360952689, 0.9415995360952689, 0.9415995360952689], None, {'mean_class_cov_gap': 0.10425135220135757, 'undercov_gap': 0.13915446454206146, 'overcov_gap': 0.05189668369030176, 'max_gap': 0.27037037037037037, 'very_undercovered': 0.4, 'marginal_cov': 0.9317073170731708, 'raw_class_coverages': [0.9796640141467727, 0.6296296296296297, 0.9241293532338308, 0.775, 0.877906976744186], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 1}, {'mean': 1.7228381374722839, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 3.0]})                 ([0.9296083674210072, 0.9296083674210072, 0.9296083674210072, 0.9296083674210072, 0.9296083674210072], None, {'mean_class_cov_gap': 0.11924919726551106, 'undercov_gap': 0.1708943439563595, 'overcov_gap': 0.04178147722923842, 'max_gap': 0.29814814814814816, 'very_undercovered': 0.4, 'marginal_cov': 0.9201773835920177, 'raw_class_coverages': [0.9743589743589743, 0.6018518518518519, 0.9092039800995025, 0.725, 0.8604651162790697], 'cluster_assignments': [-1, -1, -1, -1, -1], 'num_unclustered_classes': 3}, {'mean': 1.635920177383592, '[.25, .5, .75, .9] quantiles': [1.0, 2.0, 2.0, 2.0]})

In [ ]:
import os
import pickle
import pandas as pd
import numpy as np
from pathlib import Path

# ── Configuration ──────────────────────────────────────────────────────────
BASE_DIR = Path(
    r"C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\ddr\focal-ddr\random_calset"
)
N_TOTALCALS = [50, 100, 200, 300, 400, 500]
SCORES = ["APS", "softmax", "RAPS"]

METHODS = [
    "standard",
    "classwise",
    "exact_coverage_classwise",
    "exact_coverage_cluster",
    "cluster_proportional",
    "cluster_doubledip",
    "cluster_random",
]

# Metrics to extract from the results tuple
# tuple structure: (qhat, None, metrics_dict, setsize_dict)
# metrics_dict keys: mean_class_cov_gap, undercov_gap, overcov_gap, max_gap,
#                    very_undercovered, marginal_cov, raw_class_coverages, ...
# setsize_dict keys: mean, [.25, .5, .75, .9] quantiles

METRICS_TO_EXTRACT = [
    "marginal_cov",
    "mean_class_cov_gap",
    "undercov_gap",
    "overcov_gap",
    "max_gap",
    "very_undercovered",
]
SETSIZE_KEY = "mean"  # mean set size

OUTPUT_CSV = BASE_DIR / "ce_ddr_results_clean.csv"

# ── Helper ─────────────────────────────────────────────────────────────────
def extract_metrics(result_tuple):
    """Extract metrics from a single method's result tuple."""
    # result_tuple = (qhat, None, metrics_dict, setsize_dict)
    if result_tuple is None:
        return {}

    try:
        metrics_dict = result_tuple[2]  # 3rd element
        setsize_dict = result_tuple[3]  # 4th element
    except (IndexError, TypeError):
        return {}

    row = {}
    for key in METRICS_TO_EXTRACT:
        val = metrics_dict.get(key, np.nan)
        row[key] = float(val) if val is not None else np.nan

    # Mean set size
    if setsize_dict and SETSIZE_KEY in setsize_dict:
        row["mean_setsize"] = float(setsize_dict[SETSIZE_KEY])
    else:
        row["mean_setsize"] = np.nan

    # Set size quantiles
    quantile_key = "[.25, .5, .75, .9] quantiles"
    if setsize_dict and quantile_key in setsize_dict:
        q = setsize_dict[quantile_key]
        for i, label in enumerate(["q25", "q50", "q75", "q90"]):
            row[f"setsize_{label}"] = float(q[i]) if i < len(q) else np.nan

    return row


# ── Collect results ────────────────────────────────────────────────────────
rows = []

for n in N_TOTALCALS:
    for score in SCORES:
        score_dir = BASE_DIR / f"n_totalcal={n}" / f"score={score}"

        if not score_dir.exists():
            print(f"[WARN] Missing: {score_dir}")
            continue

        pkl_files = sorted(score_dir.glob("*.pkl"))
        if not pkl_files:
            print(f"[WARN] No pkl in: {score_dir}")
            continue

        for pkl_path in pkl_files:
            # Extract seed number from filename like "seed=0_allresults.pkl"
            fname = pkl_path.stem  # e.g. "seed=0_allresults"
            try:
                seed = int(fname.split("seed=")[1].split("_")[0])
            except (IndexError, ValueError):
                seed = fname

            try:
                with open(pkl_path, "rb") as f:
                    data = pickle.load(f)
            except Exception as e:
                print(f"[ERROR] {pkl_path}: {e}")
                continue

            for method in METHODS:
                if method not in data:
                    continue

                metrics = extract_metrics(data[method])

                row = {
                    "n_totalcal": n,
                    "score": score,
                    "seed": seed,
                    "method": method,
                }
                row.update(metrics)
                rows.append(row)

# ── Build DataFrame & save ─────────────────────────────────────────────────
df = pd.DataFrame(rows)

# Reorder columns
id_cols = ["n_totalcal", "score", "seed", "method"]
metric_cols = [c for c in df.columns if c not in id_cols]
df = df[id_cols + sorted(metric_cols)]

df.to_csv(OUTPUT_CSV, index=False)
print(f"\nSaved {len(df)} rows  →  {OUTPUT_CSV}")
print(f"\nShape: {df.shape}")
print(f"Columns: {list(df.columns)}")
print(f"\nn_totalcal values: {sorted(df['n_totalcal'].unique())}")
print(f"Scores: {sorted(df['score'].unique())}")
print(f"Seeds: {sorted(df['seed'].unique())}")
print(f"Methods: {sorted(df['method'].unique())}")
print(f"\nFirst 10 rows:")
print(df.head(10).to_string(index=False))

Saved 630 rows  →  C:\Anum\0002-Conformal-Pred-Classification\v6\FINAL\conformal\results\paper\varying_n\ddr\focal-ddr\random_calset\ce_ddr_results_clean.csv

Shape: (630, 15)
Columns: ['n_totalcal', 'score', 'seed', 'method', 'marginal_cov', 'max_gap', 'mean_class_cov_gap', 'mean_setsize', 'overcov_gap', 'setsize_q25', 'setsize_q50', 'setsize_q75', 'setsize_q90', 'undercov_gap', 'very_undercovered']

n_totalcal values: [np.int64(50), np.int64(100), np.int64(200), np.int64(300), np.int64(400), np.int64(500)]
Scores: ['APS', 'RAPS', 'softmax']
Seeds: [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4)]
Methods: ['classwise', 'cluster_doubledip', 'cluster_proportional', 'cluster_random', 'exact_coverage_classwise', 'exact_coverage_cluster', 'standard']

First 10 rows:
 n_totalcal score  seed                   method  marginal_cov  max_gap  mean_class_cov_gap  mean_setsize  overcov_gap  setsize_q25  setsize_q50  setsize_q75  setsize_q90  undercov_gap  very_undercovered
         50   APS     0                 standard      0.911752 0.344444            0.119393      1.595122     0.036405          1.0          2.0          2.0          2.0      0.174719                0.4
         50   APS     0                classwise      0.922838 0.105128            0.055524      2.881153     0.056278          2.0          3.0          3.0          4.0      0.054393                0.2
         50   APS     0 exact_coverage_classwise      0.916630 0.105128            0.039914      2.514856     0.030262          2.0          3.0          3.0          4.0      0.054393                0.2
         50   APS     0   exact_coverage_cluster      0.916186 0.344444            0.115526      1.617738     0.041148          1.0          2.0          2.0          2.0      0.165110                0.4
         50   APS     0     cluster_proportional      0.911752 0.344444            0.119393      1.595122     0.036405          1.0          2.0          2.0          2.0      0.174719                0.4
         50   APS     0        cluster_doubledip      0.911752 0.344444            0.119393      1.595122     0.036405          1.0          2.0          2.0          2.0      0.174719                0.4
         50   APS     0           cluster_random      0.916186 0.344444            0.115526      1.622616     0.041148          1.0          2.0          2.0          2.0      0.165110                0.4
         50   APS     1                 standard      0.864302 0.404348            0.180225      1.353880     0.048353          1.0          1.0          2.0          2.0      0.213193                0.6
         50   APS     1                classwise      0.881596 0.100000            0.050152      2.822616     0.060520          2.0          3.0          3.0          4.0      0.034599                0.0
         50   APS     1 exact_coverage_classwise      0.876718 0.065012            0.035909      2.517517     0.027397          2.0          3.0          3.0          4.0      0.041584                0.0